=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'date'

module YousignClientV3
  class IdDocumentVerificationStatus
    PENDING = 'pending'.freeze
    APPROVED = 'approved'.freeze
    DECLINED = 'declined'.freeze
    INCONCLUSIVE = 'inconclusive'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = IdDocumentVerificationStatus.constants.select { |c| IdDocumentVerificationStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #IdDocumentVerificationStatus" if constantValues.empty?
      value
    end
  end
end
