=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

module YousignClientV3
  class DeprecatedApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # [DEPRECATED] Upload a Document
    # Deprecated endpoint, do not use.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :file 
    # @option opts [String] :nature 
    # @option opts [String] :insert_after_id 
    # @option opts [String] :password 
    # @option opts [String] :name 
    # @option opts [InitialsArea] :initials 
    # @option opts [BOOLEAN] :parse_anchors 
    # @return [Document]
    def post_documents(opts = {})
      data, _status_code, _headers = post_documents_with_http_info(opts)
      data
    end

    # [DEPRECATED] Upload a Document
    # Deprecated endpoint, do not use.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :file 
    # @option opts [String] :nature 
    # @option opts [String] :insert_after_id 
    # @option opts [String] :password 
    # @option opts [String] :name 
    # @option opts [InitialsArea] :initials 
    # @option opts [BOOLEAN] :parse_anchors 
    # @return [Array<(Document, Integer, Hash)>] Document data, response status code and response headers
    def post_documents_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DeprecatedApi.post_documents ...'
      end
      if @api_client.config.client_side_validation && opts[:'nature'] && !['attachment', 'signable_document'].include?(opts[:'nature'])
        fail ArgumentError, 'invalid value for "nature", must be one of attachment, signable_document'
      end
      # resource path
      local_var_path = '/documents'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['multipart/form-data'])

      # form parameters
      form_params = opts[:form_params] || {}
      form_params['file'] = opts[:'file'] if !opts[:'file'].nil?
      form_params['nature'] = opts[:'nature'] if !opts[:'nature'].nil?
      form_params['insert_after_id'] = opts[:'insert_after_id'] if !opts[:'insert_after_id'].nil?
      form_params['password'] = opts[:'password'] if !opts[:'password'].nil?
      form_params['name'] = opts[:'name'] if !opts[:'name'].nil?
      form_params['initials'] = opts[:'initials'] if !opts[:'initials'].nil?
      form_params['parse_anchors'] = opts[:'parse_anchors'] if !opts[:'parse_anchors'].nil?

      # http body (model)
      post_body = opts[:body] 

      return_type = opts[:return_type] || 'Document' 

      auth_names = opts[:auth_names] || ['bearerAuth']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type)

      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DeprecatedApi#post_documents\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
