=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ArchiveApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ArchiveApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ArchiveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArchiveApi' do
    it 'should create an instance of ArchiveApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ArchiveApi)
    end
  end

  # unit tests for get_archives_archived_file_id_download
  # Download archived file
  # Download the archived file using the ArchivedFileId.
  # @param archived_file_id ArchivedFileId
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_archives_archived_file_id_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_archives
  # Direct upload an archived file
  # Archive a file in a secure digital safe for 10 years
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :workspace_id 
  # @option opts [String] :archive_y 
  # @option opts [Array<String>] :tags 
  # @option opts [String] :expired_at 
  # @return [ArchivedFile]
  describe 'post_archives test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
