=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::AuditTrailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuditTrailApi' do
  before do
    # run before each test
    @instance = YousignClientV3::AuditTrailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditTrailApi' do
    it 'should create an instance of AuditTrailApi' do
      expect(@instance).to be_instance_of(YousignClientV3::AuditTrailApi)
    end
  end

  # unit tests for get_signature_requests_signature_request_id_audit_trails_download
  # Download Signature Request Audit Trails
  # Download the PDF version of all the Audit Trails attached to a given Signature Request. Each Audit Trail is bound to a different Signer. Only possible when the Signature Request status is &#x60;done&#x60;.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :merge Download all Audit Trails merged as a single PDF file
  # @return [String]
  describe 'get_signature_requests_signature_request_id_audit_trails_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_signers_signer_id_audit_trails
  # Get Signer Audit Trail
  # Retrieves the JSON version of the Audit Trail attached to a given Signer. Only possible when Signer status is &#x60;signed&#x60;.
  # @param signature_request_id Signature Request Id
  # @param signer_id Signer Id
  # @param [Hash] opts the optional parameters
  # @return [SignerAuditTrail]
  describe 'get_signature_requests_signature_request_id_signers_signer_id_audit_trails test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signers_signer_id_audit_trails_download
  # Download Audit Trail PDF
  # Download the PDF version of the Audit Trail attached to a given Signer. Only possible when Signer status is &#x60;signed&#x60;.
  # @param signature_request_id Signature Request Id
  # @param signer_id Signer Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_signers_signer_id_audit_trails_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
