=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::BankAccountVerificationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BankAccountVerificationApi' do
  before do
    # run before each test
    @instance = YousignClientV3::BankAccountVerificationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BankAccountVerificationApi' do
    it 'should create an instance of BankAccountVerificationApi' do
      expect(@instance).to be_instance_of(YousignClientV3::BankAccountVerificationApi)
    end
  end

  # unit tests for get_bank_account_verifications_bank_account_verification_id
  # Retrieve a bank account verification
  # Get the detailed results of a bank account verification.
  # @param bank_account_verification_id The bank account verification ID
  # @param [Hash] opts the optional parameters
  # @return [BankAccountVerification]
  describe 'get_bank_account_verifications_bank_account_verification_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_bank_account_verifications
  # Initiate a new Bank Account Verification
  # Creates a new Bank Account Verification resource.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :first_name 
  # @option opts [String] :last_name 
  # @option opts [String] :file 
  # @option opts [IBAN] :iban 
  # @option opts [BIC] :bic 
  # @option opts [String] :legal_entity_name 
  # @return [BankAccountVerificationCreated]
  describe 'post_bank_account_verifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
