=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::BetaApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BetaApi' do
  before do
    # run before each test
    @instance = YousignClientV3::BetaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BetaApi' do
    it 'should create an instance of BetaApi' do
      expect(@instance).to be_instance_of(YousignClientV3::BetaApi)
    end
  end

  # unit tests for create_id_document_verification
  # Initiate a new ID document verification
  # Verify a person’s identity by sending the file containing their ID document (ID card, passport, residence permit or driving license).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :first_name 
  # @option opts [String] :last_name 
  # @option opts [String] :document_type 
  # @option opts [String] :file 
  # @option opts [String] :additional_file 
  # @return [IdDocumentVerificationCreated]
  describe 'create_id_document_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_bank_account_verifications_bank_account_verification_id
  # Retrieve a bank account verification
  # Get the detailed results of a bank account verification.
  # @param bank_account_verification_id The bank account verification ID
  # @param [Hash] opts the optional parameters
  # @return [BankAccountVerification]
  describe 'get_bank_account_verifications_bank_account_verification_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_id_document_verification
  # Retrieve an ID document verification
  # Get the detailed results of an ID document verification, including the status of the verification, the reasons in case of rejection and the data extracted from the ID document.
  # @param id_document_verification_id The ID document verification ID
  # @param [Hash] opts the optional parameters
  # @return [IdDocumentVerification]
  describe 'get_id_document_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_identity_verifications_identity_verification_id
  # Retrieve an identity verification
  # Get the detailed results of an Identity Verification.
  # @param identity_verification_id The Identity verification ID
  # @param [Hash] opts the optional parameters
  # @return [VideoIdentityVerification]
  describe 'get_identity_verifications_identity_verification_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_bank_account_verifications
  # Initiate a new Bank Account Verification
  # Creates a new Bank Account Verification resource.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :first_name 
  # @option opts [String] :last_name 
  # @option opts [String] :file 
  # @option opts [IBAN] :iban 
  # @option opts [BIC] :bic 
  # @option opts [String] :legal_entity_name 
  # @return [BankAccountVerificationCreated]
  describe 'post_bank_account_verifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_identity_verifications
  # Initiate a new Identity Verification
  # Creates a new Identity Verification resource.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateVideoIdentityVerification] :body 
  # @return [VideoIdentityVerificationCreated]
  describe 'post_identity_verifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
