=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ConsumptionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConsumptionApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ConsumptionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConsumptionApi' do
    it 'should create an instance of ConsumptionApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ConsumptionApi)
    end
  end

  # unit tests for get_consumption_addon
  # Get detailed addon consumption.
  # Retrieves detailed addon consumption for the current subscription period.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :addons A list of add-ons to filter the results on.
  # @return [GetConsumptionAddon200Response]
  describe 'get_consumption_addon test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_consumption_detail
  # Get detailed Consumption data
  # Returns the consumption of your organization over a specified period.
  # @param from The starting date for data retrieval.
  # @param to The end date for data retrieval. The &#x60;to&#x60; date must be later than the &#x60;from&#x60; date and within one year of the &#x60;from&#x60; date.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @option opts [String] :breakdown_type Specifies how data is grouped. By default, it returns the total consumption for the entire organization. If set to &#x60;workspace&#x60;, the data will be grouped by Workspace.
  # @option opts [Array<String>] :workspace_ids A list of Workspace IDs to filter the results.
  # @return [GetConsumptionDetail200Response]
  describe 'get_consumption_detail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_consumptions
  # Get Consumptions
  # Get signatures Consumption by source
  # @param from The \&quot;from\&quot; date must not be more than 1 year in the past
  # @param to The \&quot;to\&quot; date must be more recent than the \&quot;from\&quot; date
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authentication_key The API authentication key to use to retrieve the data
  # @return [Consumption]
  describe 'get_consumptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_consumptions_export
  # Export Consumption data
  # Get a binary .csv file containing all the Consumption data of the underlying signatures
  # @param from The \&quot;from\&quot; date must not be more than 1 year in the past
  # @param to The \&quot;to\&quot; date must be more recent than the \&quot;from\&quot; date
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authentication_key The API authentication key to use to retrieve the data
  # @return [String]
  describe 'get_consumptions_export test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
