=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ContactApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ContactApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactApi' do
    it 'should create an instance of ContactApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ContactApi)
    end
  end

  # unit tests for delete_contacts_contact_id
  # Delete a Contact
  # Deletes a given Contact.
  # @param contact_id Contact Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_contacts_contact_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contacts
  # List Contacts
  # Returns the list of all the Contacts within your organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @return [GetContacts200Response]
  describe 'get_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contacts_contact_id
  # Get a Contact
  # Retrieves a given Contact.
  # @param contact_id Contact Id
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'get_contacts_contact_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_contacts_contact_id
  # Update a Contact
  # Updates a given Contact. Any parameters not provided are left unchanged. 
  # @param contact_id Contact Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateContact] :body 
  # @return [Contact]
  describe 'patch_contacts_contact_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_contact
  # Create a Contact
  # Creates a new Contact.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateContact] :body 
  # @return [Contact]
  describe 'post_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
