=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::CustomExperienceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomExperienceApi' do
  before do
    # run before each test
    @instance = YousignClientV3::CustomExperienceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomExperienceApi' do
    it 'should create an instance of CustomExperienceApi' do
      expect(@instance).to be_instance_of(YousignClientV3::CustomExperienceApi)
    end
  end

  # unit tests for delete_custom_experience
  # Delete a Custom Experience
  # Deletes a given Custom Experience.
  # @param custom_experience_id Custom Experience Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_experience test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_custom_experience_logo
  # Delete a Custom Experience logo
  # Deletes the logo of a Custom Experience.
  # @param custom_experience_id Custom Experience Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_experience_logo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_custom_experiences
  # List Custom Experiences
  # Returns the list of all Custom Experiences in your Organization. You can limit the number of items returned by using pagination. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @return [GetCustomExperiences200Response]
  describe 'get_custom_experiences test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_custom_experiences_custom_experience_id
  # Get a Custom Experience
  # Retrieves a given Custom Experience.
  # @param custom_experience_id Custom Experience Id
  # @param [Hash] opts the optional parameters
  # @return [CustomExperience]
  describe 'get_custom_experiences_custom_experience_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_custom_experience_logo
  # Update a Custom Experience logo
  # Updates the logo of a given Custom Experience by uploading the image of your choice.
  # @param custom_experience_id Custom Experience Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @return [CustomExperience]
  describe 'patch_custom_experience_logo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_custom_experiences_custom_experience_id
  # Update a Custom Experience
  # Updates a given Custom Experience. Any parameters not provided are left unchanged. 
  # @param custom_experience_id Custom Experience Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateCustomExperience] :body 
  # @return [CustomExperience]
  describe 'patch_custom_experiences_custom_experience_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_custom_experience
  # Create a Custom Experience
  # Creates a new Custom Experience.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateCustomExperience] :body 
  # @return [CustomExperience]
  describe 'post_custom_experience test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
