=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::DocumentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DocumentApi' do
  before do
    # run before each test
    @instance = YousignClientV3::DocumentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentApi' do
    it 'should create an instance of DocumentApi' do
      expect(@instance).to be_instance_of(YousignClientV3::DocumentApi)
    end
  end

  # unit tests for delete_signature_requests_signature_request_id_documents_document_id
  # Delete a Document
  # Deletes a given Document from a Signature Request.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id_documents_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents
  # List Signature Request&#x27;s Documents
  # Returns a list of Documents for a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :nature Filter by nature
  # @return [Array<Document>]
  describe 'get_signature_requests_signature_request_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_document_id
  # Get a Document
  # Retrieves a given Document.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @return [Document]
  describe 'get_signature_requests_signature_request_id_documents_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_documents_id_download
  # Download a single Signature Request&#x27;s Document
  # Downloads the PDF version of a given Document.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_signature_requests_signature_request_id_documents_documents_id_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_download
  # Download Signature Request&#x27;s Documents
  # Downloads the PDF version of all Documents attached to a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :version Specify Documents version to download, &#x60;completed&#x60; is only available when the Signature Request status is &#x60;done&#x60;.
  # @option opts [BOOLEAN] :archive Force zip archive download
  # @return [String]
  describe 'get_signature_requests_signature_request_id_documents_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_signature_requests_signature_request_id_documents_document_id
  # Update a Document
  # Updates a given Document. Any parameters not provided are left unchanged.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateDocument] :body 
  # @return [Document]
  describe 'patch_signature_requests_signature_request_id_documents_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_documents
  # Add Document to a Signature Request
  # Adds a Document to a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :nature 
  # @option opts [String] :insert_after_id 
  # @option opts [String] :password 
  # @option opts [String] :name 
  # @option opts [InitialsArea] :initials 
  # @option opts [BOOLEAN] :parse_anchors 
  # @return [Document]
  describe 'post_signature_requests_signature_request_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_documents
  # Add Document to a Signature Request
  # Adds a Document to a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [CreateDocumentFromJson] :body Sending file with metadata
  # @return [Document]
  describe 'post_signature_requests_signature_request_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_documents_document_id_replace
  # Replace a Document in a Signature Request
  # Replace the file of a given Document.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :name 
  # @return [Document]
  describe 'post_signature_requests_signature_request_id_documents_document_id_replace test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
