=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ElectronicSealAuditTrailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ElectronicSealAuditTrailApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ElectronicSealAuditTrailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElectronicSealAuditTrailApi' do
    it 'should create an instance of ElectronicSealAuditTrailApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ElectronicSealAuditTrailApi)
    end
  end

  # unit tests for download_electronic_seal_audit_trail
  # Download an Electronic Seal Audit Trail
  # Electronic Seal Audit Trail is only available when the Electronic Seal is \&quot;done\&quot;.
  # @param electronic_seal_id Electronic Seal Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_electronic_seal_audit_trail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_electronic_seal_audit_trail
  # Get an Electronic Seal Audit Trail
  # Electronic Seal Audit Trail is only available when the Electronic Seal is \&quot;done\&quot;.
  # @param electronic_seal_id Electronic Seal Id
  # @param [Hash] opts the optional parameters
  # @return [ElectronicSealAuditTrail]
  describe 'get_electronic_seal_audit_trail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
