=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ElectronicSealApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ElectronicSealApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ElectronicSealApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElectronicSealApi' do
    it 'should create an instance of ElectronicSealApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ElectronicSealApi)
    end
  end

  # unit tests for get_electronic_seal
  # Get an Electronic Seal
  # Retrieves a given Electronic Seal.
  # @param electronic_seal_id Electronic Seal Id
  # @param [Hash] opts the optional parameters
  # @return [ElectronicSeal]
  describe 'get_electronic_seal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_electronic_seal_images
  # List Electronic Seal Images
  # Lists Electronic Seal Images. The list is paginated and can be filtered by the &#x60;after&#x60; cursor. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @return [ListElectronicSealImages200Response]
  describe 'list_electronic_seal_images test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_electronic_seals
  # Create an Electronic Seal
  # Create a new Electronic Seal
  # @param [Hash] opts the optional parameters
  # @option opts [CreateElectronicSealPayload] :body 
  # @return [ElectronicSeal]
  describe 'post_electronic_seals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
