=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ElectronicSealDocumentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ElectronicSealDocumentApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ElectronicSealDocumentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElectronicSealDocumentApi' do
    it 'should create an instance of ElectronicSealDocumentApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ElectronicSealDocumentApi)
    end
  end

  # unit tests for download_electronic_seal_document
  # Download an Electronic Seal Document
  # Download a given Electronic Seal Document.
  # @param electronic_seal_document_id Electronic Seal Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_electronic_seal_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_electronic_seal_document
  # Create an Electronic Seal Document
  # Create an Electronic Seal Document from an other one.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :password 
  # @return [ElectronicSealDocument]
  describe 'upload_electronic_seal_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_electronic_seal_document
  # Create an Electronic Seal Document
  # Create an Electronic Seal Document from an other one.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateElectronicSealDocumentFromJson] :body 
  # @return [ElectronicSealDocument]
  describe 'upload_electronic_seal_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
