=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::ElectronicSealImageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ElectronicSealImageApi' do
  before do
    # run before each test
    @instance = YousignClientV3::ElectronicSealImageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ElectronicSealImageApi' do
    it 'should create an instance of ElectronicSealImageApi' do
      expect(@instance).to be_instance_of(YousignClientV3::ElectronicSealImageApi)
    end
  end

  # unit tests for delete_electronic_seal_image
  # Delete an Electronic Seal Image
  # Deletes a given Electronic Seal Image.
  # @param electronic_seal_image_id Electronic Seal Image Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_electronic_seal_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for download_electronic_seal_image
  # Download an Electronic Seal Image
  # Download a given Electronic Seal Image.
  # @param electronic_seal_image_id Electronic Seal Image Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_electronic_seal_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_electronic_seal_image
  # Upload an Electronic Seal Image
  # Upload an Electronic Seal Image to use for creating an Electronic Seal (can be used for several Electronic Seals).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @option opts [String] :name 
  # @return [ElectronicSealImage]
  describe 'upload_electronic_seal_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
