=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::FieldApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FieldApi' do
  before do
    # run before each test
    @instance = YousignClientV3::FieldApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FieldApi' do
    it 'should create an instance of FieldApi' do
      expect(@instance).to be_instance_of(YousignClientV3::FieldApi)
    end
  end

  # unit tests for delete_signature_requests_signature_request_id_documents_document_id_fields_field_id
  # Delete a Field
  # Deletes a given Field from a Document.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param field_id Field Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id_documents_document_id_fields_field_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_documents_document_id_fields
  # Lists the Fields of a Signature Request Document.
  # Returns a list of Fields for a given Document. You can limit the number of items returned by using filters.
  # @param signature_request_id Signature Request Id
  # @param document_id Document ID
  # @param [Hash] opts the optional parameters
  # @option opts [Array<null>] :types Filter by Field type.
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @return [GetSignatureRequestsSignatureRequestIdDocumentsDocumentIdFields200Response]
  describe 'get_signature_requests_signature_request_id_documents_document_id_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_documents_document_id_fields
  # Create a new Field on a Document
  # Adds a Field to a given Document.
  # @param signature_request_id Signature Request Id
  # @param document_id Document ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateField] :body 
  # @return [GetSignatureRequestsSignatureRequestIdDocumentsDocumentIdFields200ResponseDataInner]
  describe 'post_signature_requests_signature_request_id_documents_document_id_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_signature_requests_signature_request_id_documents_document_id_fields_field_id
  # Update a Field
  # Updates a given Field. Any parameters not provided are left unchanged.
  # @param signature_request_id Signature Request Id
  # @param document_id Document Id
  # @param field_id Field Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateField] :body 
  # @return [GetSignatureRequestsSignatureRequestIdDocumentsDocumentIdFields200ResponseDataInner]
  describe 'update_signature_requests_signature_request_id_documents_document_id_fields_field_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
