=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::FollowerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FollowerApi' do
  before do
    # run before each test
    @instance = YousignClientV3::FollowerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FollowerApi' do
    it 'should create an instance of FollowerApi' do
      expect(@instance).to be_instance_of(YousignClientV3::FollowerApi)
    end
  end

  # unit tests for get_signature_requests_signature_request_id_followers
  # List the Signature Request&#x27;s Followers
  # Returns a list of Followers for a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @return [GetSignatureRequestsSignatureRequestIdFollowers200Response]
  describe 'get_signature_requests_signature_request_id_followers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_followers
  # Create new Followers
  # Adds a Follower to a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [Array<CreateFollowersInner>] :body 
  # @return [Array<Follower>]
  describe 'post_signature_requests_signature_request_id_followers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
