=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::IDDocumentVerificationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IDDocumentVerificationApi' do
  before do
    # run before each test
    @instance = YousignClientV3::IDDocumentVerificationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IDDocumentVerificationApi' do
    it 'should create an instance of IDDocumentVerificationApi' do
      expect(@instance).to be_instance_of(YousignClientV3::IDDocumentVerificationApi)
    end
  end

  # unit tests for create_id_document_verification
  # Initiate a new ID document verification
  # Verify a person’s identity by sending the file containing their ID document (ID card, passport, residence permit or driving license).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :first_name 
  # @option opts [String] :last_name 
  # @option opts [String] :document_type 
  # @option opts [String] :file 
  # @option opts [String] :additional_file 
  # @return [IdDocumentVerificationCreated]
  describe 'create_id_document_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_id_document_verification
  # Retrieve an ID document verification
  # Get the detailed results of an ID document verification, including the status of the verification, the reasons in case of rejection and the data extracted from the ID document.
  # @param id_document_verification_id The ID document verification ID
  # @param [Hash] opts the optional parameters
  # @return [IdDocumentVerification]
  describe 'get_id_document_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
