=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::SignerDocumentRequestApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SignerDocumentRequestApi' do
  before do
    # run before each test
    @instance = YousignClientV3::SignerDocumentRequestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SignerDocumentRequestApi' do
    it 'should create an instance of SignerDocumentRequestApi' do
      expect(@instance).to be_instance_of(YousignClientV3::SignerDocumentRequestApi)
    end
  end

  # unit tests for delete_signature_requests_signature_request_id_document_requests_document_request_id
  # Delete a Signer Document Request
  # Delete a Signer Document Request from signature request. This action is only permitted when the Signature Request is a draft.
  # @param signature_request_id Signature Request Id
  # @param document_request_id Signer Document Request Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id_document_requests_document_request_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_signature_requests_signature_request_id_document_requests_document_request_id_signers_signer_id
  # Remove a Signer to a given Signer Document Request
  # Remove a Signer to a given Signer Document Request. This action is only permitted when the Signature Request is a draft.
  # @param signature_request_id Signature Request Id
  # @param document_request_id Signer Document Request Id
  # @param signer_id Signer Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id_document_requests_document_request_id_signers_signer_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_signature_requests_signature_request_id_signers_signer_id_documents
  # Delete the Documents uploaded by a Signer
  # Deletes all documents uploaded by a given Signer for a specific Signature Request. Deletion is only possible when Signer status is &#x60;signed&#x60;. 
  # @param signature_request_id Signature Request Id
  # @param signer_id Signer Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_signature_requests_signature_request_id_signers_signer_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_signer_document_requests
  # List Signer Document Requests of the Signature Request
  # Returns a list of Signer Document Requests for a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @return [GetSignatureRequestsSignatureRequestIdSignerDocumentRequests200Response]
  describe 'get_signature_requests_signature_request_id_signer_document_requests test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_signers_signer_id_documents
  # List the Signer Documents of a Signer
  # Returns a list of Documents uploaded by a given Signer. Only possible when Signer status is &#x60;signed&#x60;. 
  # @param signature_request_id Signature Request Id
  # @param signer_id Signer Id
  # @param [Hash] opts the optional parameters
  # @return [GetSignatureRequestsSignatureRequestIdSignersSignerIdDocuments200Response]
  describe 'get_signature_requests_signature_request_id_signers_signer_id_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_signature_requests_signature_request_id_signers_signer_id_documents_signer_document_id
  # Download a Signer Document
  # Downloads a Document uploaded by a given Signer. Only possible when Signer status is &#x60;signed&#x60;. 
  # @param signature_request_id Signature Request Id
  # @param signer_id Signer Id
  # @param signer_document_id Signer Document Id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_signature_requests_signature_request_id_signers_signer_id_documents_signer_document_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_signature_requests_signature_request_id_document_requests
  # Add Signer Document Request to a Signature Request
  # Adds a Signer Document Request to a given Signature Request.
  # @param signature_request_id Signature Request Id
  # @param [Hash] opts the optional parameters
  # @option opts [CreateSignerDocumentRequest] :body 
  # @return [SignerDocumentRequest]
  describe 'post_signature_requests_signature_request_id_document_requests test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_signature_requests_signature_request_id_document_requests_document_request_id_signers_signer_id
  # Adds a Signer to a given Signer Document Request
  # Adds a Signer to a given Signer Document Request. This action is only permitted when the Signature Request is a draft.
  # @param signature_request_id Signature Request Id
  # @param document_request_id Signer Document Request Id
  # @param signer_id Signer Id
  # @param [Hash] opts the optional parameters
  # @return [SignerDocumentRequest]
  describe 'put_signature_requests_signature_request_id_document_requests_document_request_id_signers_signer_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
