=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::TemplateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TemplateApi' do
  before do
    # run before each test
    @instance = YousignClientV3::TemplateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplateApi' do
    it 'should create an instance of TemplateApi' do
      expect(@instance).to be_instance_of(YousignClientV3::TemplateApi)
    end
  end

  # unit tests for get_templates
  # List Templates
  # Returns the list of all Templates within your Organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @return [GetTemplates200Response]
  describe 'get_templates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
