=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::UserInvitationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserInvitationApi' do
  before do
    # run before each test
    @instance = YousignClientV3::UserInvitationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserInvitationApi' do
    it 'should create an instance of UserInvitationApi' do
      expect(@instance).to be_instance_of(YousignClientV3::UserInvitationApi)
    end
  end

  # unit tests for get_invitations
  # List User Invitations
  # Returns the list of all the Users Invitations within your Organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @option opts [String] :email A given e-mail address to filter on.
  # @return [GetInvitations200Response]
  describe 'get_invitations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_users_invitation_invitation_id
  # Get an Invitation
  # Retrieves a given User Invitation.
  # @param invitation_id Invitation Id
  # @param [Hash] opts the optional parameters
  # @return [UserInvitation]
  describe 'get_users_invitation_invitation_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_users_user_id_invitation
  # Get a User Invitation via the User
  # Retrieves the Invitation of a given User. The Invitation only exists when the User is in &#x60;invited&#x60; status.
  # @param user_id User Id
  # @param [Hash] opts the optional parameters
  # @return [UserInvitation]
  describe 'get_users_user_id_invitation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
