=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::UserApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @instance = YousignClientV3::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@instance).to be_instance_of(YousignClientV3::UserApi)
    end
  end

  # unit tests for delete_users_user_id
  # Delete a User
  # Deletes a given User and its Invitation, only possible when the User is in &#x60;invited&#x60; status.
  # @param user_id User Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_users_user_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_workspace_workspace_id_users_user_id
  # Remove a user from a workspace
  # Removes a User from a given Workspace.
  # @param workspace_id Workspace Id
  # @param user_id User Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_workspace_workspace_id_users_user_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_users
  # List Users
  # Returns the list of all the Users within your Organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @option opts [String] :email A given e-mail address to filter on.
  # @return [GetUsers200Response]
  describe 'get_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_users_user_id
  # Get a User
  # Retrieves a given User within your Organization.
  # @param user_id User Id
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'get_users_user_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_users_user_id
  # Update a User
  # Updates a given User. Any parameters not provided are left unchanged. 
  # @param user_id User Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateUser] :body 
  # @return [User]
  describe 'patch_users_user_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_users
  # Create a new User
  # Creates a new application User and sends them an invitation email. &#x60;email&#x60;: The email address must not match any existing User’s email. &#x60;workspaces&#x60;: The new User must be associated with at least one Workspace in the Organization. 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateUser] :body 
  # @return [User]
  describe 'post_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_workspaces_workspace_id_users
  # Associate a user to a workspace
  # Associates a User with a given Workspace.
  # @param workspace_id Workspace Id
  # @param user_id User Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'put_workspaces_workspace_id_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
