=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::WebhookApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhookApi' do
  before do
    # run before each test
    @instance = YousignClientV3::WebhookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookApi' do
    it 'should create an instance of WebhookApi' do
      expect(@instance).to be_instance_of(YousignClientV3::WebhookApi)
    end
  end

  # unit tests for delete_webhooks_webhook_id
  # Delete a Webhook subscription
  # Deletes a given Webhook subscription.
  # @param webhook_id Webhook Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_webhooks_webhook_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks
  # List Webhook subscriptions
  # Returns the list of all Webhook subscriptions in your Organization.
  # @param [Hash] opts the optional parameters
  # @return [Array<WebhookSubscription>]
  describe 'get_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhooks_webhook_id
  # Get a Webhook subscription
  # Retrieves a given Webhook subscription.
  # @param webhook_id Webhook Id
  # @param [Hash] opts the optional parameters
  # @return [WebhookSubscription]
  describe 'get_webhooks_webhook_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_webhooks_webhook_id
  # Update a Webhook subscription
  # Updates a given Webhook subscription. Any parameters not provided are left unchanged. 
  # @param webhook_id Webhook Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateWebhookSubscription] :body 
  # @return [WebhookSubscription]
  describe 'patch_webhooks_webhook_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_webhooks_subscriptions
  # Create a Webhook subscription
  # Creates a new Webhook subscription in your organization.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateWebhookSubscription] :body 
  # @return [WebhookSubscription]
  describe 'post_webhooks_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
