=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for YousignClientV3::WorkspaceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WorkspaceApi' do
  before do
    # run before each test
    @instance = YousignClientV3::WorkspaceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkspaceApi' do
    it 'should create an instance of WorkspaceApi' do
      expect(@instance).to be_instance_of(YousignClientV3::WorkspaceApi)
    end
  end

  # unit tests for delete_workspace
  # Delete a Workspace
  # Deletes a given Workspace and transfers everything that is attached to this Workspace to a another specified Workspace.
  # @param workspace_id Workspace Id
  # @param [Hash] opts the optional parameters
  # @option opts [DeleteWorkspace] :body 
  # @return [nil]
  describe 'delete_workspace test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_workspaces
  # List Workspaces
  # Returns the list of all Workspaces within your Organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after After cursor (pagination)
  # @option opts [Integer] :limit The limit of items count to retrieve.
  # @return [GetWorkspaces200Response]
  describe 'get_workspaces test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_workspaces_default
  # Get the default Workspace
  # Retrieves the default Workspace.
  # @param [Hash] opts the optional parameters
  # @return [Workspace]
  describe 'get_workspaces_default test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_workspaces_workspace_id
  # Get a Workspace
  # Retrieves a given Workspace.
  # @param workspace_id Workspace Id
  # @param [Hash] opts the optional parameters
  # @return [Workspace]
  describe 'get_workspaces_workspace_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for mark_workspace_as_default
  # Mark the given Workspace as default
  # Marks the given Workspace as default.
  # @param [Hash] opts the optional parameters
  # @option opts [MarkWorkspaceAsDefault] :body 
  # @return [nil]
  describe 'mark_workspace_as_default test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_workspaces_workspace_id
  # Update a Workspace
  # Updates a given Workspace. Any parameters not provided are left unchanged. 
  # @param workspace_id Workspace Id
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateWorkspace] :body 
  # @return [Workspace]
  describe 'patch_workspaces_workspace_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_workspace
  # Create a Workspace
  # Creates a new Workspace in the organization.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateWorkspace] :body 
  # @return [Workspace]
  describe 'post_workspace test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
