=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

OpenAPI spec version: 3.0
Contact: contact@yousign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YousignClientV3::EmailNotification1
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmailNotification1' do
  before do
    # run before each test
    @instance = YousignClientV3::EmailNotification1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailNotification1' do
    it 'should create an instance of EmailNotification1' do
      expect(@instance).to be_instance_of(YousignClientV3::EmailNotification1)
    end
  end
  describe 'test attribute "disabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["signer.signature_request_canceled_due_to_an_error.signer_who_has_not_signed", "signer.signature_request_canceled_due_to_an_error.signer_who_has_already_signed", "signer.signature_request_canceled_by_sender.signer_who_has_not_signed", "signer.signature_request_canceled_by_sender.signer_who_has_already_signed", "signer.signature_request_done.signature_request_contains_one_signer", "signer.signature_request_done.signature_request_contains_multiple_signers", "signer.signature_request_with_multiple_signers_signed.signed_by_a_signer", "signer.signature_request_updated.new_expiration_date", "signer.signature_request_updated_by_sender.new_signer_details", "signer.signature_request_signature_requested.first_notification", "signer.signature_request_signature_requested.reminder_to_sign"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.disabled = value }.not_to raise_error
      # end
    end
  end

end
